BibliotecaVirtual/Areas/Biblioteca/Controllers/AuthorController.cs
using BibliotecaVirtual.Application.Enums;
using BibliotecaVirtual.Application.Interfaces;
using BibliotecaVirtual.Application.ViewModels;
using BibliotecaVirtual.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BibliotecaVirtual.Areas.Biblioteca.Controllers
{
    [Authorize]
    [Area("Biblioteca")]
    public class AuthorController : BaseController
    {
        private readonly IAuthorService _authorService;

        #region Construtor

        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        } 

        #endregion

        #region Métodos de View

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var authors = await _authorService.ObtainAuthors();
            return View(nameof(Index), authors);
        }

        [Authorize(Roles = UserRoles.Moderator)]
        [HttpGet]
        public IActionResult Add()
        {
            return View(nameof(Edit), new AuthorViewModel());
        }

        [Authorize(Roles = UserRoles.Moderator)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AuthorViewModel viewModel)
        {
            var author = await _authorService.AddAuthor(viewModel);

            if (_authorService.IsSuccessful() == false)
            {
                AddModelError(_authorService.GetModelErrors());
                return View(nameof(Edit), author);
            }

            return RedirectToAction(nameof(Edit), new { author.AuthorId });
        }

        [Authorize(Roles = UserRoles.Moderator)]
        [HttpGet]
        public async Task<IActionResult> Edit(int authorId)
        {
            var author = await _authorService.ObtainAuthor(authorId);
            return View(nameof(Edit), author);
        }

        [Authorize(Roles = UserRoles.Moderator)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AuthorViewModel viewModel)
        {
            var author = await _authorService.UpdateAuthor(viewModel);

            if (_authorService.IsSuccessful() == false)
            {
                AddModelError(_authorService.GetModelErrors());
                return View(nameof(Edit), author);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles = UserRoles.Moderator)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int authorId)
        {
            await _authorService.DeleteAuthor(authorId);

            if (_authorService.IsSuccessful() == false)
            {
                AddModelError(_authorService.GetModelErrors());
            }

            return RedirectToAction(nameof(Index));
        } 

        #endregion

        #region Métodos de Api

        public async Task<IActionResult> GetAuthors()
        {
            var authors = await _authorService.ObtainAuthors();
            return ReturnApi(true, string.Empty, authors);
        }

        #endregion
    }
}

BibliotecaVirtual/Areas/Biblioteca/Controllers/BookController.cs
using BibliotecaVirtual.Application.Interfaces;
using BibliotecaVirtual.Application.ViewModels;
using BibliotecaVirtual.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BibliotecaVirtual.Areas.Biblioteca.Controllers
{
    [Authorize]
    [Area("Biblioteca")]
    public class BookController : BaseController
    {
        private readonly IBookService _bookService;

        #region Construtor

        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }

        #endregion

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(nameof(Index), null);
        }

        public async Task<IActionResult> GetBooks(string filter)
        {
            var books = await _bookService.ObtainBooks(filter);
            return ReturnApi(true, string.Empty, books);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(nameof(Edit), new BookViewModel());
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(BookViewModel viewModel)
        {
            var book = await _bookService.AddBook(viewModel);

            if (_bookService.IsSuccessful() == false)
            {
                AddModelError(_bookService.GetModelErrors());
                return View(nameof(Edit), book);
            }

            return RedirectToAction(nameof(Edit), new { book.BookId});
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int bookId)
        {
            if(bookId <= 0)
            {
                AddModelError("Livro não encontrado");
                return View(nameof(Edit), new BookViewModel());
            }

            var book = await _bookService.ObtainBook(bookId);
            return View(nameof(Edit), book);
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookViewModel viewModel)
        {
            var book = await _bookService.UpdateBook(viewModel);

            if (_bookService.IsSuccessful() == false)
            {
                AddModelError(_bookService.GetModelErrors());
                return View(nameof(Edit), book);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [Route("book/rent")]
        public async Task<IActionResult> Rent(int bookId)
        {
            var book = await _bookService.RentBook(bookId);

            if (_bookService.IsSuccessful() == true)
            {
                return ReturnApi(true, string.Empty, book);
            }
            else
            {
                return ReturnApi(false, _bookService.GetModelErrors());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int bookId)
        {
            await _bookService.DeleteBook(bookId);

            if (_bookService.IsSuccessful() == false)
            {
                AddModelError(_bookService.GetModelErrors());
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

BibliotecaVirtual/Areas/Biblioteca/Controllers/CategoryController.cs
using BibliotecaVirtual.Application.Interfaces;
using BibliotecaVirtual.Application.ViewModels;
using BibliotecaVirtual.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BibliotecaVirtual.Areas.Biblioteca.Controllers
{
    [Authorize]
    [Area("Biblioteca")]
    public class CategoryController : BaseController
    {
        private readonly ICategoryService _categoryService;

        #region Construtor

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        } 

        #endregion

        #region Métodos de View

        public async Task<IActionResult> Index()
        {
            var categories = await _categoryService.ObtainCategories();
            return View(nameof(Index), categories);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(nameof(Edit), new CategoryViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CategoryViewModel viewModel)
        {
            var category = await _categoryService.AddCategory(viewModel);

            if (_categoryService.IsSuccessful() == false)
            {
                AddModelError(_categoryService.GetModelErrors());
                return View(nameof(Edit), category);
            }

            return RedirectToAction(nameof(Edit), new { category.CategoryId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int CategoryId)
        {
            var category = await _categoryService.ObtainCategory(CategoryId);
            return View(nameof(Edit), category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryViewModel viewModel)
        {
            var category = await _categoryService.UpdateCategory(viewModel);

            if (_categoryService.IsSuccessful() == false)
            {
                AddModelError(_categoryService.GetModelErrors());
                return View(nameof(Edit), category);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int CategoryId)
        {
            await _categoryService.DeleteCategory(CategoryId);

            if (_categoryService.IsSuccessful() == false)
            {
                AddModelError(_categoryService.GetModelErrors());
            }

            return RedirectToAction(nameof(Index));
        } 

        #endregion

        #region Métodos de Api

        public async Task<IActionResult> GetCategories()
        {
            var categories = await _categoryService.ObtainCategories();
            return ReturnApi(true, string.Empty, categories);
        }

        #endregion
    }
}

BibliotecaVirtual/Areas/Biblioteca/Controllers/PublisherController.cs
using BibliotecaVirtual.Application.Interfaces;
using BibliotecaVirtual.Application.ViewModels;
using BibliotecaVirtual.Controllers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BibliotecaVirtual.Areas.Biblioteca.Controllers
{
    [Authorize]
    [Area("Biblioteca")]
    public class PublisherController : BaseController
    {
        private readonly IPublisherService _publisherService;

        #region Construtor

        public PublisherController(IPublisherService publisherService)
        {
            _publisherService = publisherService;
        } 

        #endregion

        #region Métodos de View

        public async Task<IActionResult> Index()
        {
            var publishers = await _publisherService.ObtainPublishers();
            return View(nameof(Index), publishers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(nameof(Edit), new PublisherViewModel());
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(PublisherViewModel viewModel)
        {
            var publisher = await _publisherService.AddPublisher(viewModel);

            if (_publisherService.IsSuccessful() == false)
            {
                AddModelError(_publisherService.GetModelErrors());
                return View(nameof(Edit), publisher);
            }

            return RedirectToAction(nameof(Edit), new { publisher.PublisherId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int PublisherId)
        {
            var publisher = await _publisherService.ObtainPublisher(PublisherId);
            return View(nameof(Edit), publisher);
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PublisherViewModel viewModel)
        {
            var publisher = await _publisherService.UpdatePublisher(viewModel);

            if (_publisherService.IsSuccessful() == false)
            {
                AddModelError(_publisherService.GetModelErrors());
                return View(nameof(Edit), publisher);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int PublisherId)
        {
            await _publisherService.DeletePublisher(PublisherId);

            if (_publisherService.IsSuccessful() == false)
            {
                AddModelError(_publisherService.GetModelErrors());
            }

            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Métodos de Api

        public async Task<IActionResult> GetPublishers()
        {
            var publishers = await _publisherService.ObtainPublishers();
            return ReturnApi(true, string.Empty, publishers);
        }        

        #endregion
    }
}

BibliotecaVirtual/Views/Shared/_FormButtons.cshtml
@model FormButtonsViewModel

@{
    var ActionName = Html.ActionName();
    var tagRoute = $"asp-route-{@Model.FormKey}='{@Model.FormValue}";
}

<div class="form-group">
    <footer class="cadastro-botoes">
        <section class="float-right">
            <a id="botaoRetornar" class="btn btn-light btn-outline-dark cursor-pointer" tabindex="0"
               asp-action="Index"
               data-original-title="Retornar para a consulta." data-container="body">
                Retornar
            </a>
            <input class="btn btn-success text-light" type="submit" value="Salvar" />
            @if (ActionName == "Edit")
            {
                <input id="cadastro-botao-excluir" class="btn btn-danger text-light  cursor-pointer"
                       name="Excluir" value="Delete" formaction="Delete" formmethod="post" type="submit" />
            }
        </section>
    </footer>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function ()
        {
            var excluir = document.getElementById('cadastro-botao-excluir');
            if (excluir)
            {
                var url = '?@(Model.FormKey)=' + @Model.FormValue;
                excluir.href += url;
            }
        });

        function FormDelete(e)
        {
            e.preventDefault();
            var frm = document.getElementById('cadastro-botao-excluir').form;
            frm.action = 'Delete';

            try
            {
                /** Envia informações para o servidor. */
                $(frm).submit();
            }
            catch (exception)
            {
                console.log(exception);
            }
        }
    </script>
</div>

BibliotecaVirtual/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca Virtual</title>

    @{ await Html.RenderPartialAsync("_Styles"); }
</head>
<body>
    @{ await Html.RenderPartialAsync("_Navigation"); }

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Biblioteca Virtual - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>

    @{ await Html.RenderPartialAsync("_Scripts"); }
    @RenderSection("Scripts", required: false)
</body>
</html>

BibliotecaVirtual/Views/Shared/_Navigation.cshtml
<cache vary-by-header="Version" vary-by-user="true">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                
                <a class="navbar-brand text-light"
                   asp-area=""
                   asp-controller="Home"
                   asp-action="Index">Editora<img class="logo-app" src="~/img/todo-4783676_640.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" 
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light"
                               asp-area="Biblioteca"
                               asp-controller="Book"
                               asp-action="Index">Livros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light"
                               asp-area="Biblioteca"
                               asp-controller="Category"
                               asp-action="Index">Gêneros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light"
                               asp-area="Biblioteca"
                               asp-controller="Author"
                               asp-action="Index">Autores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light"
                               asp-area="Biblioteca"
                               asp-controller="Publisher"
                               asp-action="Index">Editoras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light"
                               asp-area=""
                               asp-controller="Home"
                               asp-action="Contact">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light"
                               asp-area=""
                               asp-controller="Home"
                               asp-action="About">Sobre</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
</cache>

BibliotecaVirtual/Views/Shared/_Scripts.cshtml
@if (System.Diagnostics.Debugger.IsAttached == true)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/popper/popper.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" asp-append-version="true"
            asp-fallback-src="~/lib/vue/vue.js"
            asp-fallback-test="Vue.version"></script>
    <script src="~/js/bundles/biblioteca.js" asp-append-version="true"></script>
}
else
{
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="~/lib/popper/popper.min.js" asp-append-version="true"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js" asp-append-version="true"
            asp-fallback-src="~/lib/vue/vue.min.js"
            asp-fallback-test="Vue.version"></script>
    <script src="~/js/bundles/biblioteca.min.js" asp-append-version="true"></script>
}
<partial name="_ValidationScriptsPartial" />

BibliotecaVirtual/Views/Shared/_Styles.cshtml
@if (System.Diagnostics.Debugger.IsAttached == true)
{
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/bundles/biblioteca.css"  asp-append-version="true" />
}
else
{
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/bundles/biblioteca.min.css" asp-append-version="true" />
}

BibliotecaVirtual/Views/Shared/_ValidationSummary.cshtml
@{ var visivel = ViewData.ModelState.ErrorCount > decimal.Zero ? string.Empty : "hidden"; }

<div id="#summary" class="sumario alert alert-danger" @visivel>
    <i class="fa-fw fa fa-exclamation-triangle"></i>
    <button type="button" class="sumario-fechar close" onclick="$('div.sumario.alert').hide()">×</button>
    <h5 id="mensagem-sumario">Verifique as informações do formulário e tente novamente!</h5>
    <div class="sumario-lista" asp-validation-summary="All"></div>
</div>